spring:
  application:
    name: configuracion
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rpacheco124/MicroServicios-Demo-MultiCliente
          search-paths: config-git
server:
  port: 8888