version: '3'
services: 
  postgresql:
    image: postgres
    container_name: PostgreSql
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=Password"
    volumes:
      - "./docker-data/:/docker-entrypoint-initdb.d/"
  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdmin4
    ports:
      - "8090:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=Password"
#volumes:
#  psqlvol: