---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicios_demo
    username: postgres
    password: Password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
config-server:
  url: http://localhost:8888/
